### ISSUE TITLE
Set the default language in the settings

### ISSUE THREAD

**Issue by nicoursi** [ElishaAz/Sayboard#20]
It would be nice to have the possibility to set the default language from the settings. I use 90% of the times Italian, so having to switch everytime I open sayboard takes time

**Comment by Tombstone2K** [comment]
Yes, that would be really welcome.

**Comment by Maetih** [comment]
Thanks for this great app! Starting with version 4.2.0. the selection of the default language via the globe symbol is however not working anymore. With version 4.1.2. it is still working. I experienced this problem on a Samsung Tablet SM-T225 and a Google Pixel 6a, both running Android 14. It would be nice, if this could be fixed again, because without default language selector the app mostly outputs the wrong language, if several are installed.
