### ISSUE TITLE
Option / Description to add Newline as label to Right / Left Keys settings

### ISSUE THREAD

**Issue by zos2022** [ElishaAz/Sayboard#49]
It is great that Sayboard now has customizable Left or Right Keys settings, thanks a lot!

I tried to add Newline as a label, but it seems that is not possible (it is not saved).
Or is it already possible, but I missed to find out what the correct text for it is?

**Comment by ElishaAz** [comment]
There was a bug with how the newline character was encoded which I fixed.

By the way, if you put a newline as the label, you won't actually see anything. That's why I added the label / text. You're supposed to put the newline in the text, and put something visible, e.g. ⮑ (U+2B91) or ⤷ (U+2937) in the label.
